"""Protocol interfaces for all services in the DI container."""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class IConfigService(Protocol):
    """Application configuration."""

    @property
    def paper_mode(self) -> bool: ...
    @property
    def exchange(self) -> str: ...
    @property
    def timeframe(self) -> str: ...
    @property
    def account_balance(self) -> float: ...
    @property
    def max_positions(self) -> int: ...
    @property
    def max_risk_per_trade_pct(self) -> float: ...
    @property
    def telegram_enabled(self) -> bool: ...
    @property
    def telegram_token(self) -> str: ...
    @property
    def telegram_chat_id(self) -> str: ...
    @property
    def telegram_timeout(self) -> int: ...
    @property
    def telegram_retry(self) -> int: ...
    @property
    def scanner_threads(self) -> int: ...
    @property
    def scanner_top_n(self) -> int: ...
    @property
    def scanner_min_volume(self) -> float: ...
    @property
    def decision_top_n(self) -> int: ...
    @property
    def min_rr(self) -> float: ...
    @property
    def max_rr(self) -> float: ...
    @property
    def min_probability(self) -> float: ...
    @property
    def max_atr_pct(self) -> float: ...
    @property
    def min_volume_24h(self) -> float: ...
    @property
    def stop_atr_multiplier(self) -> float: ...
    @property
    def stop_fixed_pct(self) -> float: ...
    @property
    def max_position_size_pct(self) -> float: ...
    @property
    def trail_atr_multiplier(self) -> float: ...
    @property
    def max_holding_candles(self) -> int: ...
    @property
    def tp1_sell_pct(self) -> float: ...
    @property
    def tp2_sell_pct(self) -> float: ...
    @property
    def tp3_sell_pct(self) -> float: ...
    @property
    def taker_fee(self) -> float: ...
    @property
    def maker_fee(self) -> float: ...
    @property
    def slippage_bps(self) -> int: ...
    @property
    def data_dir(self) -> str: ...
    @property
    def logs_dir(self) -> str: ...


@runtime_checkable
class IExchangeManager(Protocol):
    """Exchange connection management (provider interface for multi-exchange)."""

    @property
    def name(self) -> str: ...
    def get_ticker(self, symbol: str) -> dict[str, Any]: ...
    def fetch_ohlcv(self, symbol: str, timeframe: str = "1h", limit: int = 200) -> list: ...
    def fetch_balance(self) -> dict[str, Any]: ...
    def get_markets(self) -> list[dict[str, Any]]: ...
    def health_check(self) -> bool: ...
    def set_active(self, name: str) -> None: ...
    def list_providers(self) -> list[str]: ...
    def list_connected(self) -> dict[str, bool]: ...
    def get_provider(self, name: Optional[str] = None) -> Any: ...
    def load_markets(self) -> dict[str, Any]: ...
    def fetch_tickers(self, symbols: Optional[list[str]] = None) -> dict[str, Any]: ...
    def has(self, feature: str) -> bool: ...


@runtime_checkable
class IWalletManager(Protocol):
    """Wallet balance and equity (provider interface for paper/live)."""

    @property
    def balance(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def free_balance(self) -> float: ...
    @property
    def realized_pnl(self) -> float: ...
    @property
    def unrealized_pnl(self) -> float: ...
    @property
    def net_pnl(self) -> float: ...
    @property
    def total_return_pct(self) -> float: ...
    def reserve(self, amount: float) -> None: ...
    def release(self, amount: float) -> None: ...
    def deduct(self, amount: float) -> None: ...
    def add(self, amount: float) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...


@runtime_checkable
class IScanner(Protocol):
    """Market scanner."""

    def run(self) -> dict[str, Any]: ...
    def get_results(self) -> dict[str, Any]: ...


@runtime_checkable
class IStrategyManager(Protocol):
    """Strategy and decision engine."""

    def evaluate(self, scanner_results: dict[str, Any]) -> list[dict[str, Any]]: ...
    def get_decisions(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class IRiskManager(Protocol):
    """Risk assessment and trade approval."""

    def approve(self, decisions: list[dict[str, Any]], wallet: IWalletManager, positions: Any) -> list[dict[str, Any]]: ...
    def get_approved(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class IOrderManager(Protocol):
    """Order execution — only component allowed to create BUY/SELL orders."""

    def execute(self, trade_plan: Any, **kwargs: Any) -> Any: ...
    def get_orders(self) -> list[dict[str, Any]]: ...
    @property
    def mode(self) -> str: ...
    def set_mode(self, mode: str) -> None: ...
    def enable_live(self) -> None: ...
    def disable_live(self) -> None: ...
    def is_live_enabled(self) -> bool: ...
    def validate_live_ready(self) -> Optional[str]: ...
    def sync_paper_state(self, result: Any) -> None: ...
    def get_metrics_summary(self) -> dict[str, Any]: ...
    def get_audit_trail(self, limit: int = 100) -> list[Any]: ...


@runtime_checkable
class IPositionManager(Protocol):
    """Position lifecycle management — single owner of open positions."""

    def get_open_positions(self) -> list[dict[str, Any]]: ...
    def simulate(self, plan: dict[str, Any], current_price: float, **kwargs) -> dict[str, Any]: ...
    def update_positions(self, current_prices: dict[str, float]) -> list[dict[str, Any]]: ...
    def get_all(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class INotificationManager(Protocol):
    """Notification sender — only component allowed to send messages."""

    def send(self, message: str) -> bool: ...
    def notify_buy(self, symbol: str, entry_price: float, quantity: float,
                   position_size: float, stop_loss: float, tp1: float) -> None: ...
    def notify_close(self, symbol: str, pnl: float, reason: str, exit_price: float) -> None: ...
    def notify_error(self, error: str) -> None: ...
    def notify_trade_rejected(self, symbol: str, reason: str) -> None: ...
    def notify_system(self, message: str) -> None: ...


@runtime_checkable
class IHealthMonitor(Protocol):
    """System health monitoring."""

    @property
    def uptime_sec(self) -> int: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
    def force_refresh(self) -> dict[str, Any]: ...


@runtime_checkable
class IMetricsManager(Protocol):
    """Performance metrics — single source of truth for all bot stats."""

    def record_trade(self, order: dict[str, Any]) -> None: ...
    def get_metrics(self) -> dict[str, Any]: ...
    def reset(self) -> None: ...
    def summary(self) -> dict[str, Any]: ...
    def balance_snapshot(self) -> dict[str, Any]: ...
    def balance(self) -> float: ...
    def equity(self) -> float: ...
    def realized_pnl(self) -> float: ...
    def unrealized_pnl(self) -> float: ...
    def net_pnl(self) -> float: ...
    def total_return_pct(self) -> float: ...
    def total_trades(self) -> int: ...
    def winning_trades(self) -> int: ...
    def losing_trades(self) -> int: ...
    def win_rate(self) -> float: ...
    def profit_factor(self) -> float: ...
    def gross_profit(self) -> float: ...
    def gross_loss(self) -> float: ...
    def open_positions_count(self) -> int: ...
    def closed_positions_count(self) -> int: ...
    def open_positions(self) -> list[dict[str, Any]]: ...
    def all_positions(self) -> list[dict[str, Any]]: ...
    def closed_orders(self) -> list[dict[str, Any]]: ...
    def best_trade(self) -> dict[str, Any]: ...
    def worst_trade(self) -> dict[str, Any]: ...
